namespace Riptide.LowLevel.TextEngine.Harfbuzz;

public enum hb_ot_metrics_tag_t {
    HORIZONTAL_ASCENDER = (byte)'h' << 24 | (byte)'a' << 16 | (byte)'s' << 8 | (byte)'c',
    HORIZONTAL_DESCENDER = (byte)'h' << 24 | (byte)'d' << 16 | (byte)'s' << 8 | (byte)'c',
    HORIZONTAL_LINE_GAP = (byte)'h' << 24 | (byte)'l' << 16 | (byte)'g' << 8 | (byte)'p',
    HORIZONTAL_CLIPPING_ASCENT = (byte)'h' << 24 | (byte)'c' << 16 | (byte)'l' << 8 | (byte)'a',
    HORIZONTAL_CLIPPING_DESCENT = (byte)'h' << 24 | (byte)'c' << 16 | (byte)'l' << 8 | (byte)'d',
    VERTICAL_ASCENDER = (byte)'v' << 24 | (byte)'a' << 16 | (byte)'s' << 8 | (byte)'c',
    VERTICAL_DESCENDER = (byte)'v' << 24 | (byte)'d' << 16 | (byte)'s' << 8 | (byte)'c',
    VERTICAL_LINE_GAP = (byte)'v' << 24 | (byte)'l' << 16 | (byte)'g' << 8 | (byte)'p',
    HORIZONTAL_CARET_RISE	= (byte)'h' << 24 | (byte)'c' << 16 | (byte)'r' << 8 | (byte)'s',
    HORIZONTAL_CARET_RUN = (byte)'h' << 24 | (byte)'c' << 16 | (byte)'r' << 8 | (byte)'n',
    HORIZONTAL_CARET_OFFSET = (byte)'h' << 24 | (byte)'c' << 16 | (byte)'o' << 8 | (byte)'f',
    VERTICAL_CARET_RISE = (byte)'v' << 24 | (byte)'c' << 16 | (byte)'r' << 8 | (byte)'s',
    VERTICAL_CARET_RUN = (byte)'v' << 24 | (byte)'c' << 16 | (byte)'r' << 8 | (byte)'n',
    VERTICAL_CARET_OFFSET	= (byte)'v' << 24 | (byte)'c' << 16 | (byte)'o' << 8 | (byte)'f',
    X_HEIGHT = (byte)'x' << 24 | (byte)'h' << 16 | (byte)'g' << 8 | (byte)'t',
    CAP_HEIGHT = (byte)'c' << 24 | (byte)'p' << 16 | (byte)'h' << 8 | (byte)'t',
    SUBSCRIPT_EM_X_SIZE = (byte)'s' << 24 | (byte)'b' << 16 | (byte)'x' << 8 | (byte)'s',
    SUBSCRIPT_EM_Y_SIZE = (byte)'s' << 24 | (byte)'b' << 16 | (byte)'y' << 8 | (byte)'s',
    SUBSCRIPT_EM_X_OFFSET	= (byte)'s' << 24 | (byte)'b' << 16 | (byte)'x' << 8 | (byte)'o',
    SUBSCRIPT_EM_Y_OFFSET	= (byte)'s' << 24 | (byte)'b' << 16 | (byte)'y' << 8 | (byte)'o',
    SUPERSCRIPT_EM_X_SIZE	= (byte)'s' << 24 | (byte)'p' << 16 | (byte)'x' << 8 | (byte)'s',
    SUPERSCRIPT_EM_Y_SIZE	= (byte)'s' << 24 | (byte)'p' << 16 | (byte)'y' << 8 | (byte)'s',
    SUPERSCRIPT_EM_X_OFFSET = (byte)'s' << 24 | (byte)'p' << 16 | (byte)'x' << 8 | (byte)'o',
    SUPERSCRIPT_EM_Y_OFFSET = (byte)'s' << 24 | (byte)'p' << 16 | (byte)'y' << 8 | (byte)'o',
    STRIKEOUT_SIZE = (byte)'s' << 24 | (byte)'t' << 16 | (byte)'r' << 8 | (byte)'s',
    STRIKEOUT_OFFSET = (byte)'s' << 24 | (byte)'t' << 16 | (byte)'r' << 8 | (byte)'o',
    UNDERLINE_SIZE = (byte)'u' << 24 | (byte)'n' << 16 | (byte)'d' << 8 | (byte)'s',
    UNDERLINE_OFFSET = (byte)'u' << 24 | (byte)'n' << 16 | (byte)'d' << 8 | (byte)'o',
}