[assembly: AssemblyDescription("A library contains common runtime API for both player and editor.")]
[assembly: InternalsVisibleTo("RiptidePlayer")]
[assembly: InternalsVisibleTo("RiptideEditor")]
[assembly: InternalsVisibleTo("RiptideEditorV2")]
[assembly: InternalsVisibleTo("RenderingExperiment")]