global using RiptideEngine.Core.Utils;
global using RPCSToolkit.Utilities;
global using Silk.NET.Core.Attributes;
global using Silk.NET.Core.Native;
global using Silk.NET.Direct3D12;
global using Silk.NET.DXGI;
global using Silk.NET.Windowing;
global using System.Buffers;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using RiptideMathematics;

global using D3D12Feature = Silk.NET.Direct3D12.Feature;
global using D3D12InfoQueueFilter = Silk.NET.Direct3D12.InfoQueueFilter;
global using D3D12Range = Silk.NET.Direct3D12.Range;
global using D3D12ResourceStates = Silk.NET.Direct3D12.ResourceStates;
global using D3D12Viewport = Silk.NET.Direct3D12.Viewport;